---
- name: restart postfix
  service: name=postfix state=restarted

- name: postmap sender_canonical
  command: postmap {{ postfix_sender_canonical_file }}

- name: postmap transport
  command: postmap {{ postfix_transport_file }}

- name: postifx upgrade-configuration
  command: postfix upgrade-configuration
